# Generated by Django 2.0.2 on 2018-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estatus',
            field=models.BooleanField(default='Pagado'),
        ),
    ]
