# Generated by Django 2.0.2 on 2018-10-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20181001_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estatus',
            field=models.BooleanField(),
        ),
    ]
