# Generated by Django 2.0.2 on 2018-10-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20181001_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='estatus',
        ),
        migrations.AddField(
            model_name='pago',
            name='pagado',
            field=models.NullBooleanField(),
        ),
    ]
