# Generated by Django 2.0.2 on 2018-10-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20181001_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='facturación',
        ),
        migrations.AddField(
            model_name='clientes',
            name='facturacion',
            field=models.NullBooleanField(),
        ),
    ]
